export const dummyBooks = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0-7432-7356-5",
    category: "Fiction",
    publishYear: 1925,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/91-YY6-Lh7L._AC_UY218_.jpg",
    description: "A classic American novel set in the Jazz Age",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    category: "Fiction",
    publishYear: 1960,
    totalCopies: 4,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/71d8gc8rF-L._AC_UY218_.jpg",
    description: "A powerful story of racial injustice and childhood innocence",
  },
  {
    id: "3",
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    isbn: "978-0-596-51774-8",
    category: "Technology",
    publishYear: 2008,
    totalCopies: 3,
    availableCopies: 1,
    coverImage:
      "https://m.media-amazon.com/images/I/91YlBt-bCHL._AC_UY218_.jpg",
    description: "Essential JavaScript programming techniques",
  },
  {
    id: "4",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0-13-235088-4",
    category: "Technology",
    publishYear: 2008,
    totalCopies: 6,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/81KpjloJJZL._AC_UY218_.jpg",
    description: "A handbook of agile software craftsmanship",
  },
  {
    id: "5",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0-553-38016-3",
    category: "Science",
    publishYear: 1988,
    totalCopies: 3,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81o5zZ5vRmL._AC_UY218_.jpg",
    description: "Exploring the universe from the Big Bang to black holes",
  },
  {
    id: "6",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0-452-28423-4",
    category: "Fiction",
    publishYear: 1949,
    totalCopies: 5,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/71K9U31Ok9L._AC_UY218_.jpg",
    description:
      "A dystopian novel about totalitarian surveillance and control",
  },
  {
    id: "7",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    isbn: "978-0-201-61622-4",
    category: "Technology",
    publishYear: 1999,
    totalCopies: 4,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/518FqJvR9aL._AC_UY218_.jpg",
    description: "Best practices for effective software development",
  },
  {
    id: "8",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    category: "History",
    publishYear: 2011,
    totalCopies: 6,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UY218_.jpg",
    description:
      "The journey of humans from ancient times to modern civilization",
  },
  {
    id: "9",
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "978-0-7352-1129-2",
    category: "Self-Help",
    publishYear: 2018,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/91bYsX41DVL._AC_UY218_.jpg",
    description: "An easy & proven way to build good habits & break bad ones",
  },
  {
    id: "10",
    title: "The Art of War",
    author: "Sun Tzu",
    isbn: "978-1-4165-0028-0",
    category: "Philosophy",
    publishYear: -500,
    totalCopies: 4,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81wgcld4wxL._AC_UY218_.jpg",
    description: "Ancient strategies for warfare and leadership",
  },
  {
    id: "11",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "978-0-374-53355-7",
    category: "Psychology",
    publishYear: 2011,
    totalCopies: 6,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/71w1EHRaUBL._AC_UY218_.jpg",
    description: "Explores the dual systems of thought and decision-making",
  },
  {
    id: "12",
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "978-0-06-112241-5",
    category: "Fiction",
    publishYear: 1988,
    totalCopies: 5,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UY218_.jpg",
    description: "A journey of dreams, destiny, and self-discovery",
  },
  {
    id: "13",
    title: "Deep Work",
    author: "Cal Newport",
    isbn: "978-1-4555-8661-2",
    category: "Self-Help",
    publishYear: 2016,
    totalCopies: 4,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81pViX3XfWL._AC_UY218_.jpg",
    description: "Rules for focused success in a distracted world",
  },
  {
    id: "14",
    title: "A Promised Land",
    author: "Barack Obama",
    isbn: "978-1-5247-6316-9",
    category: "Biography",
    publishYear: 2020,
    totalCopies: 6,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/919oWnzxKJL._AC_UY218_.jpg",
    description: "The memoir of former U.S. President Barack Obama",
  },
  {
    id: "15",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    isbn: "978-1-57731-480-6",
    category: "Spirituality",
    publishYear: 1997,
    totalCopies: 5,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/71RrCbtjWIL._AC_UY218_.jpg",
    description: "A guide to spiritual enlightenment and presence",
  },
  {
    id: "16",
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "978-0-307-88789-4",
    category: "Business",
    publishYear: 2011,
    totalCopies: 6,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/81-QB7nDh4L._AC_UY218_.jpg",
    description: "Entrepreneurial strategies for building scalable startups",
  },
  {
    id: "17",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    isbn: "978-0-8070-1429-5",
    category: "Psychology",
    publishYear: 1946,
    totalCopies: 4,
    availableCopies: 1,
    coverImage:
      "https://m.media-amazon.com/images/I/71HMyqG6MRL._AC_UY218_.jpg",
    description: "A Holocaust survivor’s lessons on purpose and resilience",
  },
  {
    id: "18",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    isbn: "978-1-61268-019-4",
    category: "Finance",
    publishYear: 1997,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UY218_.jpg",
    description: "Personal finance and investing principles",
  },
  {
    id: "19",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    isbn: "978-0-06-245771-4",
    category: "Self-Help",
    publishYear: 2016,
    totalCopies: 5,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UY218_.jpg",
    description: "A counterintuitive approach to living a good life",
  },
  {
    id: "20",
    title: "Zero to One",
    author: "Peter Thiel",
    isbn: "978-0-8041-3929-8",
    category: "Business",
    publishYear: 2014,
    totalCopies: 4,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81rttXKf2iL._AC_UY218_.jpg",
    description: "Startup thinking and the future of innovation",
  },
  {
    id: "21",
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0-441-17271-9",
    category: "Science Fiction",
    publishYear: 1965,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/91dSMhdIzTL._AC_UY218_.jpg",
    description: "A science fiction epic of politics, power, and prophecy",
  },
  {
    id: "22",
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    isbn: "978-0-9847828-5-7",
    category: "Technology",
    publishYear: 2015,
    totalCopies: 6,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/51CRjf1gMFL._AC_UY218_.jpg",
    description: "189 programming questions and solutions for interviews",
  },
  {
    id: "23",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "978-0-85719-909-2",
    category: "Finance",
    publishYear: 2020,
    totalCopies: 6,
    availableCopies: 5,
    coverImage:
      "https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UY218_.jpg",
    description: "Timeless lessons on wealth, greed, and happiness",
  },
  {
    id: "24",
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "978-0-14-044933-4",
    category: "Philosophy",
    publishYear: 180,
    totalCopies: 3,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81zHkU5RH0L._AC_UY218_.jpg",
    description: "Stoic reflections by a Roman emperor on life and leadership",
  },
  {
    id: "25",
    title: "Start With Why",
    author: "Simon Sinek",
    isbn: "978-1-59184-644-4",
    category: "Business",
    publishYear: 2009,
    totalCopies: 4,
    availableCopies: 1,
    coverImage:
      "https://m.media-amazon.com/images/I/61jVQYxqg1L._AC_UY218_.jpg",
    description: "Leaders inspire action by starting with 'why'",
  },
  {
    id: "26",
    title: "The Four Agreements",
    author: "Don Miguel Ruiz",
    isbn: "978-1-878424-31-0",
    category: "Spirituality",
    publishYear: 1997,
    totalCopies: 5,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/81bGKUa1e0L._AC_UY218_.jpg",
    description: "A practical guide to personal freedom and peace",
  },
  {
    id: "27",
    title: "Hooked: How to Build Habit-Forming Products",
    author: "Nir Eyal",
    isbn: "978-1-59184-778-6",
    category: "Technology",
    publishYear: 2014,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/81Zfwr5D3cL._AC_UY218_.jpg",
    description: "The psychology behind addictive digital products",
  },
  {
    id: "28",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    isbn: "978-0-06-055566-5",
    category: "Finance",
    publishYear: 1949,
    totalCopies: 6,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/71j8b5h7+hL._AC_UY218_.jpg",
    description: "The foundational book on value investing",
  },
  {
    id: "29",
    title: "Educated",
    author: "Tara Westover",
    isbn: "978-0-399-59050-4",
    category: "Biography",
    publishYear: 2018,
    totalCopies: 5,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/81WojUxbbFL._AC_UY218_.jpg",
    description: "A memoir of a woman who escapes her survivalist family",
  },
  {
    id: "30",
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    isbn: "978-0-671-02703-2",
    category: "Self-Help",
    publishYear: 1936,
    totalCopies: 7,
    availableCopies: 5,
    coverImage:
      "https://m.media-amazon.com/images/I/81Otwki3Y-L._AC_UY218_.jpg",
    description:
      "Timeless principles for effective communication and leadership",
  },
  {
    id: "31",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0-618-00221-3",
    category: "Fantasy",
    publishYear: 1937,
    totalCopies: 6,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UY218_.jpg",
    description: "A fantasy adventure that precedes The Lord of the Rings",
  },
  {
    id: "32",
    title: "Can't Hurt Me",
    author: "David Goggins",
    isbn: "978-1-5445-1228-0",
    category: "Biography",
    publishYear: 2018,
    totalCopies: 5,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/71pWzhdJNwL._AC_UY218_.jpg",
    description: "The inspiring life story of a Navy SEAL and ultra-athlete",
  },
  {
    id: "33",
    title: "Steal Like an Artist",
    author: "Austin Kleon",
    isbn: "978-0-7611-6925-7",
    category: "Creativity",
    publishYear: 2012,
    totalCopies: 4,
    availableCopies: 2,
    coverImage:
      "https://m.media-amazon.com/images/I/61J9sOM3YLL._AC_UY218_.jpg",
    description: "Creative advice for artists and creators",
  },
  {
    id: "34",
    title: "Rework",
    author: "Jason Fried & David Heinemeier Hansson",
    isbn: "978-0-307-45374-3",
    category: "Business",
    publishYear: 2010,
    totalCopies: 5,
    availableCopies: 3,
    coverImage:
      "https://m.media-amazon.com/images/I/81RjVvU7h6L._AC_UY218_.jpg",
    description: "Unconventional advice on running a business",
  },
  {
    id: "35",
    title: "Tools of Titans",
    author: "Tim Ferriss",
    isbn: "978-1-329-18859-1",
    category: "Self-Help",
    publishYear: 2016,
    totalCopies: 6,
    availableCopies: 4,
    coverImage:
      "https://m.media-amazon.com/images/I/81bPK7sJ+lL._AC_UY218_.jpg",
    description: "Tactics, routines, and habits of high achievers",
  },
];

export const dummyMembers = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+1-555-0123",
    address: "123 Main St, City, State 12345",
    joinDate: "2024-01-15",
    membershipType: "student",
    isActive: true,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+1-555-0456",
    address: "456 Oak Ave, City, State 12345",
    joinDate: "2024-02-20",
    membershipType: "faculty",
    isActive: true,
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob.johnson@email.com",
    phone: "+1-555-0789",
    address: "789 Pine Rd, City, State 12345",
    joinDate: "2024-03-10",
    membershipType: "general",
    isActive: true,
  },
  {
    id: "4",
    name: "Alice Brown",
    email: "alice.brown@email.com",
    phone: "+1-555-0321",
    address: "321 Elm St, City, State 12345",
    joinDate: "2024-01-05",
    membershipType: "student",
    isActive: false,
  },
];

export const dummyBorrowRecords = [
  {
    id: "1",
    bookId: "1",
    memberId: "1",
    borrowDate: "2024-12-01",
    dueDate: "2024-12-15",
    status: "borrowed",
  },
  {
    id: "2",
    bookId: "2",
    memberId: "2",
    borrowDate: "2024-11-20",
    dueDate: "2024-12-04",
    status: "overdue",
    fineAmount: 5.0,
  },
  {
    id: "3",
    bookId: "3",
    memberId: "3",
    borrowDate: "2024-11-15",
    dueDate: "2024-11-29",
    returnDate: "2024-11-28",
    status: "returned",
  },
];

export const dummyStats = {
  totalBooks: 50,
  totalMembers: 25,
  borrowedBooks: 12,
  overdueBooks: 3,
  availableBooks: 38,
  monthlyBorrows: 45,
};

export const dummyUsers = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@librento.com",
    phone: "+1-555-0001",
    password: "admin123",
    isVerified: true,
    role: "admin",
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+1-555-0123",
    password: "user123",
    isVerified: true,
    role: "user",
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+1-555-0456",
    password: "user123",
    isVerified: true,
    role: "user",
    createdAt: "2024-02-20",
  },
];
